"""Build the narration timeline from the per-line voice WAVs.

Usage: python3 tools/build_timeline.py
  1. transcribes each assets/voice/<id>.wav with whisper-cli (cached in build/)
  2. applies caption fixes (caption-fixes.json) to the word list
  3. schedules lines back to back with script.json's lineGap
  4. writes timing.js (consumed by index.html) and build/narration.wav
"""

import json
import re
import subprocess
import sys
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
WHISPER_MODEL = Path.home() / ".cache/hyperframes/whisper/models/ggml-small.en.bin"
LEAD_IN = 0.4  # silence before the first line
TAIL = 1.2  # hold after the last line


def wav_info(path: Path) -> tuple[float, int]:
    with wave.open(str(path)) as w:
        return w.getnframes() / w.getframerate(), w.getframerate()


def transcribe(wav: Path) -> list[dict]:
    out = BUILD / wav.stem
    json_path = out.with_suffix(".json")
    if not json_path.exists() or json_path.stat().st_mtime < wav.stat().st_mtime:
        subprocess.run(
            ["whisper-cli", "-m", str(WHISPER_MODEL), "-f", str(wav),
             "-ml", "1", "-sow", "-oj", "-of", str(out), "-np"],
            check=True, capture_output=True,
        )
    segments = json.loads(json_path.read_text())["transcription"]
    words = []
    for seg in segments:
        text = seg["text"].strip()
        if text:
            words.append({"text": text,
                          "start": seg["offsets"]["from"] / 1000,
                          "end": seg["offsets"]["to"] / 1000})
    return words


def apply_fixes(words: list[dict], fixes: list[dict]) -> list[dict]:
    """Each fix replaces a run of words (matched case-insensitively) with one display word."""
    result, i = [], 0
    while i < len(words):
        for fix in fixes:
            n = len(fix["match"])
            run = [w["text"].lower() for w in words[i:i + n]]
            if run == [m.lower() for m in fix["match"]]:
                result.append({"text": fix["display"], "start": words[i]["start"], "end": words[i + n - 1]["end"]})
                i += n
                break
        else:
            result.append(dict(words[i]))
            i += 1
    return result


def lowercase(words: list[dict], stems: list[str]) -> list[dict]:
    def fix(text: str) -> str:
        core = re.sub(r"[^\w']", "", text).lower()
        return text.lower() if core in stems else text
    return [{**w, "text": fix(w["text"])} for w in words]


def mix(lines: list[dict], total: float, rate: int) -> None:
    frames = bytearray(int(total * rate) * 2)
    for line in lines:
        with wave.open(str(ROOT / line["audio"])) as w:
            if w.getsampwidth() != 2 or w.getnchannels() != 1:
                sys.exit(f"{line['audio']}: expected 16-bit mono")
            data = w.readframes(w.getnframes())
        offset = int(line["start"] * rate) * 2
        frames[offset:offset + len(data)] = data
    with wave.open(str(BUILD / "narration.wav"), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(bytes(frames))


def main() -> None:
    BUILD.mkdir(exist_ok=True)
    cfg = json.loads((ROOT / "script.json").read_text())
    fixes = json.loads((ROOT / "caption-fixes.json").read_text())
    lines, cursor, rate = [], LEAD_IN, 24000
    for line in cfg["lines"]:
        wav = ROOT / "assets/voice" / f"{line['id']}.wav"
        duration, rate = wav_info(wav)
        words = apply_fixes(transcribe(wav), fixes.get(line["id"], []) + fixes.get("all", []))
        words = lowercase(words, fixes.get("lowercase", []))
        lines.append({"id": line["id"], "scene": line["scene"], "audio": f"assets/voice/{wav.name}",
                      "start": round(cursor, 3), "duration": round(duration, 3), "words": words})
        cursor += duration + cfg["lineGap"]
    total = round(cursor - cfg["lineGap"] + TAIL, 3)
    mix(lines, total, rate)
    payload = {"duration": total, "fps": 30, "lines": lines}
    (ROOT / "timing.js").write_text(
        "// Generated by tools/build_timeline.py — do not edit by hand.\n"
        f"window.TIMING = {json.dumps(payload, indent=1)};\n")
    for line in lines:
        print(f"{line['id']} @ {line['start']:7.2f}s  {line['duration']:5.2f}s  "
              + " ".join(w["text"] for w in line["words"]))
    print(f"total {total:.2f}s")


if __name__ == "__main__":
    main()
