// Generated by tools/build_timeline.py — do not edit by hand.
window.TIMING = {
 "duration": 251.976,
 "fps": 30,
 "lines": [
  {
   "id": "01",
   "scene": "Functions as values",
   "audio": "assets/voice/01.wav",
   "start": 0.4,
   "duration": 27.259,
   "words": [
    {
     "text": "Functional",
     "start": 0.1,
     "end": 0.89
    },
    {
     "text": "programming",
     "start": 0.89,
     "end": 1.86
    },
    {
     "text": "in",
     "start": 1.86,
     "end": 2.07
    },
    {
     "text": "C++",
     "start": 2.07,
     "end": 2.38
    },
    {
     "text": "is",
     "start": 2.38,
     "end": 2.54
    },
    {
     "text": "a",
     "start": 2.54,
     "end": 2.66
    },
    {
     "text": "style,",
     "start": 2.66,
     "end": 3.28
    },
    {
     "text": "not",
     "start": 3.28,
     "end": 3.46
    },
    {
     "text": "a",
     "start": 3.46,
     "end": 3.52
    },
    {
     "text": "separate",
     "start": 3.52,
     "end": 4.13
    },
    {
     "text": "language.",
     "start": 4.13,
     "end": 4.93
    },
    {
     "text": "It",
     "start": 4.93,
     "end": 5.04
    },
    {
     "text": "rests",
     "start": 5.04,
     "end": 5.35
    },
    {
     "text": "on",
     "start": 5.35,
     "end": 5.47
    },
    {
     "text": "three",
     "start": 5.47,
     "end": 5.8
    },
    {
     "text": "pillars.",
     "start": 5.8,
     "end": 6.8
    },
    {
     "text": "Pure",
     "start": 6.8,
     "end": 7.04
    },
    {
     "text": "functions",
     "start": 7.04,
     "end": 7.56
    },
    {
     "text": "return",
     "start": 7.56,
     "end": 7.91
    },
    {
     "text": "the",
     "start": 7.91,
     "end": 8.18
    },
    {
     "text": "same",
     "start": 8.18,
     "end": 8.34
    },
    {
     "text": "output",
     "start": 8.34,
     "end": 8.72
    },
    {
     "text": "for",
     "start": 8.72,
     "end": 9.07
    },
    {
     "text": "the",
     "start": 9.07,
     "end": 9.08
    },
    {
     "text": "same",
     "start": 9.08,
     "end": 9.42
    },
    {
     "text": "input.",
     "start": 9.42,
     "end": 10.0
    },
    {
     "text": "Immutable",
     "start": 10.0,
     "end": 10.69
    },
    {
     "text": "data",
     "start": 10.69,
     "end": 11.0
    },
    {
     "text": "is",
     "start": 11.0,
     "end": 11.15
    },
    {
     "text": "transformed",
     "start": 11.15,
     "end": 12.04
    },
    {
     "text": "instead",
     "start": 12.04,
     "end": 12.67
    },
    {
     "text": "of",
     "start": 12.67,
     "end": 12.77
    },
    {
     "text": "modified.",
     "start": 12.77,
     "end": 13.68
    },
    {
     "text": "And",
     "start": 13.68,
     "end": 13.9
    },
    {
     "text": "higher-order",
     "start": 13.9,
     "end": 14.48
    },
    {
     "text": "functions",
     "start": 14.48,
     "end": 14.96
    },
    {
     "text": "take",
     "start": 14.96,
     "end": 15.27
    },
    {
     "text": "or",
     "start": 15.27,
     "end": 15.32
    },
    {
     "text": "return",
     "start": 15.32,
     "end": 15.66
    },
    {
     "text": "other",
     "start": 15.66,
     "end": 16.05
    },
    {
     "text": "functions.",
     "start": 16.05,
     "end": 17.04
    },
    {
     "text": "Since",
     "start": 17.04,
     "end": 17.63
    },
    {
     "text": "C++11,",
     "start": 17.63,
     "end": 18.6
    },
    {
     "text": "lambdas,",
     "start": 18.6,
     "end": 19.23
    },
    {
     "text": "std::function,",
     "start": 19.23,
     "end": 20.31
    },
    {
     "text": "the",
     "start": 20.31,
     "end": 20.51
    },
    {
     "text": "algorithm",
     "start": 20.51,
     "end": 21.11
    },
    {
     "text": "header",
     "start": 21.11,
     "end": 21.51
    },
    {
     "text": "and",
     "start": 21.51,
     "end": 21.88
    },
    {
     "text": "constexpr",
     "start": 21.88,
     "end": 22.39
    },
    {
     "text": "make",
     "start": 22.39,
     "end": 22.56
    },
    {
     "text": "that",
     "start": 22.56,
     "end": 22.82
    },
    {
     "text": "style",
     "start": 22.82,
     "end": 23.42
    },
    {
     "text": "practical.",
     "start": 23.42,
     "end": 24.04
    },
    {
     "text": "Let's",
     "start": 24.04,
     "end": 24.32
    },
    {
     "text": "walk",
     "start": 24.32,
     "end": 24.55
    },
    {
     "text": "through",
     "start": 24.55,
     "end": 24.96
    },
    {
     "text": "seven",
     "start": 24.96,
     "end": 25.25
    },
    {
     "text": "questions",
     "start": 25.25,
     "end": 25.78
    },
    {
     "text": "interviewers",
     "start": 25.78,
     "end": 26.48
    },
    {
     "text": "actually",
     "start": 26.48,
     "end": 26.95
    },
    {
     "text": "ask.",
     "start": 26.95,
     "end": 27.2
    }
   ]
  },
  {
   "id": "02",
   "scene": "Map, filter, reduce",
   "audio": "assets/voice/02.wav",
   "start": 28.259,
   "duration": 29.475,
   "words": [
    {
     "text": "Start",
     "start": 0.09,
     "end": 0.45
    },
    {
     "text": "with",
     "start": 0.45,
     "end": 0.81
    },
    {
     "text": "the",
     "start": 0.81,
     "end": 1.08
    },
    {
     "text": "toolkit.",
     "start": 1.08,
     "end": 1.91
    },
    {
     "text": "Transform",
     "start": 1.91,
     "end": 2.5
    },
    {
     "text": "is",
     "start": 2.5,
     "end": 2.63
    },
    {
     "text": "map,",
     "start": 2.63,
     "end": 2.97
    },
    {
     "text": "copy_if",
     "start": 2.97,
     "end": 3.37
    },
    {
     "text": "is",
     "start": 3.37,
     "end": 3.48
    },
    {
     "text": "filter",
     "start": 3.48,
     "end": 4.01
    },
    {
     "text": "and",
     "start": 4.01,
     "end": 4.08
    },
    {
     "text": "accumulate",
     "start": 4.08,
     "end": 4.72
    },
    {
     "text": "is",
     "start": 4.72,
     "end": 4.98
    },
    {
     "text": "reduce.",
     "start": 4.98,
     "end": 5.76
    },
    {
     "text": "Each",
     "start": 5.76,
     "end": 6.04
    },
    {
     "text": "one",
     "start": 6.04,
     "end": 6.25
    },
    {
     "text": "driven",
     "start": 6.25,
     "end": 6.67
    },
    {
     "text": "by",
     "start": 6.67,
     "end": 6.81
    },
    {
     "text": "a",
     "start": 6.81,
     "end": 6.88
    },
    {
     "text": "small",
     "start": 6.88,
     "end": 7.53
    },
    {
     "text": "lambda.",
     "start": 7.53,
     "end": 7.88
    },
    {
     "text": "constexpr",
     "start": 7.88,
     "end": 8.73
    },
    {
     "text": "pushes",
     "start": 8.73,
     "end": 8.92
    },
    {
     "text": "pure",
     "start": 8.92,
     "end": 9.16
    },
    {
     "text": "computation",
     "start": 9.16,
     "end": 9.91
    },
    {
     "text": "to",
     "start": 9.91,
     "end": 10.06
    },
    {
     "text": "compile",
     "start": 10.06,
     "end": 10.56
    },
    {
     "text": "time.",
     "start": 10.56,
     "end": 11.36
    },
    {
     "text": "So",
     "start": 11.36,
     "end": 11.52
    },
    {
     "text": "a",
     "start": 11.52,
     "end": 11.58
    },
    {
     "text": "static_assert",
     "start": 11.58,
     "end": 12.54
    },
    {
     "text": "can",
     "start": 12.54,
     "end": 13.12
    },
    {
     "text": "prove",
     "start": 13.12,
     "end": 13.14
    },
    {
     "text": "that",
     "start": 13.14,
     "end": 13.45
    },
    {
     "text": "factorial",
     "start": 13.45,
     "end": 14.3
    },
    {
     "text": "of",
     "start": 14.3,
     "end": 14.33
    },
    {
     "text": "five",
     "start": 14.33,
     "end": 14.61
    },
    {
     "text": "is",
     "start": 14.61,
     "end": 14.76
    },
    {
     "text": "120.",
     "start": 14.76,
     "end": 15.66
    },
    {
     "text": "And",
     "start": 15.66,
     "end": 15.8
    },
    {
     "text": "a",
     "start": 15.8,
     "end": 15.84
    },
    {
     "text": "lambda",
     "start": 15.84,
     "end": 16.16
    },
    {
     "text": "that",
     "start": 16.16,
     "end": 16.39
    },
    {
     "text": "returns",
     "start": 16.39,
     "end": 16.71
    },
    {
     "text": "a",
     "start": 16.71,
     "end": 16.8
    },
    {
     "text": "lambda",
     "start": 16.8,
     "end": 17.24
    },
    {
     "text": "gives",
     "start": 17.24,
     "end": 17.61
    },
    {
     "text": "you",
     "start": 17.61,
     "end": 17.83
    },
    {
     "text": "currying.",
     "start": 17.83,
     "end": 18.64
    },
    {
     "text": "Multiply",
     "start": 18.64,
     "end": 19.21
    },
    {
     "text": "by",
     "start": 19.21,
     "end": 19.35
    },
    {
     "text": "two",
     "start": 19.35,
     "end": 19.77
    },
    {
     "text": "produces",
     "start": 19.77,
     "end": 20.17
    },
    {
     "text": "a",
     "start": 20.17,
     "end": 20.23
    },
    {
     "text": "brand",
     "start": 20.23,
     "end": 20.6
    },
    {
     "text": "new",
     "start": 20.6,
     "end": 20.88
    },
    {
     "text": "function",
     "start": 20.88,
     "end": 21.4
    },
    {
     "text": "that",
     "start": 21.4,
     "end": 21.66
    },
    {
     "text": "doubles.",
     "start": 21.66,
     "end": 22.32
    },
    {
     "text": "Functional",
     "start": 22.32,
     "end": 22.98
    },
    {
     "text": "and",
     "start": 22.98,
     "end": 23.18
    },
    {
     "text": "object-oriented",
     "start": 23.18,
     "end": 24.17
    },
    {
     "text": "styles",
     "start": 24.17,
     "end": 24.57
    },
    {
     "text": "are",
     "start": 24.57,
     "end": 24.77
    },
    {
     "text": "not",
     "start": 24.77,
     "end": 25.29
    },
    {
     "text": "rivals.",
     "start": 25.29,
     "end": 25.6
    },
    {
     "text": "C++",
     "start": 25.6,
     "end": 25.93
    },
    {
     "text": "is",
     "start": 25.93,
     "end": 26.15
    },
    {
     "text": "multi-paradigm,",
     "start": 26.15,
     "end": 27.85
    },
    {
     "text": "and",
     "start": 27.85,
     "end": 28.15
    },
    {
     "text": "good",
     "start": 28.15,
     "end": 28.24
    },
    {
     "text": "code",
     "start": 28.24,
     "end": 28.48
    },
    {
     "text": "mixes",
     "start": 28.48,
     "end": 28.96
    },
    {
     "text": "both.",
     "start": 29.07,
     "end": 29.46
    }
   ]
  },
  {
   "id": "03",
   "scene": "Scope the lock to a lambda",
   "audio": "assets/voice/03.wav",
   "start": 58.333,
   "duration": 30.501,
   "words": [
    {
     "text": "Question",
     "start": 0.09,
     "end": 0.72
    },
    {
     "text": "two,",
     "start": 0.72,
     "end": 1.1
    },
    {
     "text": "build",
     "start": 1.1,
     "end": 1.36
    },
    {
     "text": "a",
     "start": 1.36,
     "end": 1.41
    },
    {
     "text": "safe",
     "start": 1.41,
     "end": 1.62
    },
    {
     "text": "locking",
     "start": 1.62,
     "end": 1.99
    },
    {
     "text": "interface",
     "start": 1.99,
     "end": 2.52
    },
    {
     "text": "with",
     "start": 2.52,
     "end": 2.68
    },
    {
     "text": "a",
     "start": 2.68,
     "end": 2.72
    },
    {
     "text": "higher",
     "start": 2.72,
     "end": 2.97
    },
    {
     "text": "order",
     "start": 2.97,
     "end": 3.28
    },
    {
     "text": "function.",
     "start": 3.28,
     "end": 4.08
    },
    {
     "text": "Manual",
     "start": 4.08,
     "end": 4.49
    },
    {
     "text": "lock",
     "start": 4.49,
     "end": 4.76
    },
    {
     "text": "and",
     "start": 4.76,
     "end": 5.1
    },
    {
     "text": "unlock",
     "start": 5.1,
     "end": 5.37
    },
    {
     "text": "breaks",
     "start": 5.37,
     "end": 5.78
    },
    {
     "text": "the",
     "start": 5.78,
     "end": 5.98
    },
    {
     "text": "moment",
     "start": 5.98,
     "end": 6.39
    },
    {
     "text": "the",
     "start": 6.39,
     "end": 6.6
    },
    {
     "text": "work",
     "start": 6.6,
     "end": 6.86
    },
    {
     "text": "throws",
     "start": 6.86,
     "end": 7.36
    },
    {
     "text": "or",
     "start": 7.36,
     "end": 7.4
    },
    {
     "text": "returns",
     "start": 7.4,
     "end": 8.18
    },
    {
     "text": "early,",
     "start": 8.18,
     "end": 8.34
    },
    {
     "text": "and",
     "start": 8.34,
     "end": 8.44
    },
    {
     "text": "the",
     "start": 8.44,
     "end": 8.62
    },
    {
     "text": "mutex",
     "start": 8.62,
     "end": 8.92
    },
    {
     "text": "stays",
     "start": 8.92,
     "end": 9.3
    },
    {
     "text": "locked",
     "start": 9.3,
     "end": 9.95
    },
    {
     "text": "forever.",
     "start": 9.95,
     "end": 10.52
    },
    {
     "text": "Instead,",
     "start": 10.52,
     "end": 11.18
    },
    {
     "text": "write",
     "start": 11.18,
     "end": 11.53
    },
    {
     "text": "with_lock.",
     "start": 11.53,
     "end": 12.36
    },
    {
     "text": "It",
     "start": 12.36,
     "end": 12.48
    },
    {
     "text": "takes",
     "start": 12.48,
     "end": 12.84
    },
    {
     "text": "a",
     "start": 12.84,
     "end": 13.02
    },
    {
     "text": "mutex",
     "start": 13.02,
     "end": 13.16
    },
    {
     "text": "and",
     "start": 13.16,
     "end": 13.28
    },
    {
     "text": "a",
     "start": 13.28,
     "end": 13.36
    },
    {
     "text": "callable,",
     "start": 13.36,
     "end": 14.35
    },
    {
     "text": "creates",
     "start": 14.35,
     "end": 14.54
    },
    {
     "text": "a",
     "start": 14.54,
     "end": 14.63
    },
    {
     "text": "lock_guard,",
     "start": 14.63,
     "end": 15.32
    },
    {
     "text": "invokes",
     "start": 15.32,
     "end": 15.78
    },
    {
     "text": "the",
     "start": 15.78,
     "end": 15.98
    },
    {
     "text": "callable",
     "start": 15.98,
     "end": 16.5
    },
    {
     "text": "and",
     "start": 16.5,
     "end": 16.7
    },
    {
     "text": "returns",
     "start": 16.7,
     "end": 17.17
    },
    {
     "text": "its",
     "start": 17.17,
     "end": 17.37
    },
    {
     "text": "result.",
     "start": 17.37,
     "end": 18.04
    },
    {
     "text": "The",
     "start": 18.04,
     "end": 18.23
    },
    {
     "text": "critical",
     "start": 18.23,
     "end": 18.75
    },
    {
     "text": "section",
     "start": 18.75,
     "end": 19.2
    },
    {
     "text": "is",
     "start": 19.2,
     "end": 19.33
    },
    {
     "text": "now",
     "start": 19.33,
     "end": 19.52
    },
    {
     "text": "exactly",
     "start": 19.52,
     "end": 20.0
    },
    {
     "text": "the",
     "start": 20.0,
     "end": 20.29
    },
    {
     "text": "lambda",
     "start": 20.29,
     "end": 20.71
    },
    {
     "text": "body.",
     "start": 20.71,
     "end": 21.28
    },
    {
     "text": "The",
     "start": 21.28,
     "end": 21.46
    },
    {
     "text": "lock",
     "start": 21.46,
     "end": 21.7
    },
    {
     "text": "is",
     "start": 21.7,
     "end": 21.83
    },
    {
     "text": "always",
     "start": 21.83,
     "end": 22.18
    },
    {
     "text": "released,",
     "start": 22.18,
     "end": 22.79
    },
    {
     "text": "even",
     "start": 22.79,
     "end": 23.03
    },
    {
     "text": "on",
     "start": 23.03,
     "end": 23.15
    },
    {
     "text": "exceptions",
     "start": 23.15,
     "end": 23.96
    },
    {
     "text": "and",
     "start": 23.96,
     "end": 24.1
    },
    {
     "text": "callers",
     "start": 24.1,
     "end": 24.34
    },
    {
     "text": "cannot",
     "start": 24.34,
     "end": 24.66
    },
    {
     "text": "forget",
     "start": 24.66,
     "end": 25.04
    },
    {
     "text": "to",
     "start": 25.13,
     "end": 25.17
    },
    {
     "text": "unlock.",
     "start": 25.17,
     "end": 25.75
    },
    {
     "text": "A",
     "start": 25.75,
     "end": 25.81
    },
    {
     "text": "try_with_lock",
     "start": 25.81,
     "end": 26.52
    },
    {
     "text": "variant",
     "start": 26.52,
     "end": 26.98
    },
    {
     "text": "returns",
     "start": 26.98,
     "end": 27.44
    },
    {
     "text": "an",
     "start": 27.44,
     "end": 27.57
    },
    {
     "text": "optional,",
     "start": 27.57,
     "end": 28.21
    },
    {
     "text": "which",
     "start": 28.21,
     "end": 28.55
    },
    {
     "text": "is",
     "start": 28.55,
     "end": 28.68
    },
    {
     "text": "empty",
     "start": 28.68,
     "end": 29.14
    },
    {
     "text": "when",
     "start": 29.14,
     "end": 29.27
    },
    {
     "text": "the",
     "start": 29.27,
     "end": 29.46
    },
    {
     "text": "lock",
     "start": 29.46,
     "end": 29.8
    },
    {
     "text": "is",
     "start": 29.8,
     "end": 29.94
    },
    {
     "text": "busy.",
     "start": 29.94,
     "end": 30.44
    }
   ]
  },
  {
   "id": "04",
   "scene": "Type erasure, by hand",
   "audio": "assets/voice/04.wav",
   "start": 89.435,
   "duration": 34.789,
   "words": [
    {
     "text": "Question",
     "start": 0.08,
     "end": 0.72
    },
    {
     "text": "3,",
     "start": 0.72,
     "end": 1.11
    },
    {
     "text": "What",
     "start": 1.11,
     "end": 1.34
    },
    {
     "text": "is",
     "start": 1.34,
     "end": 1.45
    },
    {
     "text": "std::function",
     "start": 1.45,
     "end": 2.39
    },
    {
     "text": "and",
     "start": 2.39,
     "end": 2.56
    },
    {
     "text": "how",
     "start": 2.56,
     "end": 2.74
    },
    {
     "text": "would",
     "start": 2.74,
     "end": 3.02
    },
    {
     "text": "you",
     "start": 3.02,
     "end": 3.19
    },
    {
     "text": "build",
     "start": 3.19,
     "end": 3.74
    },
    {
     "text": "one?",
     "start": 3.74,
     "end": 3.84
    },
    {
     "text": "It",
     "start": 3.84,
     "end": 3.97
    },
    {
     "text": "is",
     "start": 3.97,
     "end": 4.12
    },
    {
     "text": "a",
     "start": 4.12,
     "end": 4.16
    },
    {
     "text": "type-erased",
     "start": 4.16,
     "end": 4.9
    },
    {
     "text": "wrapper,",
     "start": 4.9,
     "end": 5.49
    },
    {
     "text": "for",
     "start": 5.49,
     "end": 5.69
    },
    {
     "text": "any",
     "start": 5.69,
     "end": 5.89
    },
    {
     "text": "callable",
     "start": 5.89,
     "end": 6.43
    },
    {
     "text": "with",
     "start": 6.43,
     "end": 6.75
    },
    {
     "text": "a",
     "start": 6.75,
     "end": 6.76
    },
    {
     "text": "given",
     "start": 6.76,
     "end": 7.1
    },
    {
     "text": "signature.",
     "start": 7.1,
     "end": 7.84
    },
    {
     "text": "The",
     "start": 7.84,
     "end": 8.05
    },
    {
     "text": "trick",
     "start": 8.05,
     "end": 8.41
    },
    {
     "text": "is",
     "start": 8.41,
     "end": 8.55
    },
    {
     "text": "a",
     "start": 8.55,
     "end": 8.62
    },
    {
     "text": "non-template",
     "start": 8.62,
     "end": 9.48
    },
    {
     "text": "abstract",
     "start": 9.48,
     "end": 10.06
    },
    {
     "text": "base,",
     "start": 10.06,
     "end": 10.52
    },
    {
     "text": "with",
     "start": 10.52,
     "end": 10.82
    },
    {
     "text": "virtual",
     "start": 10.82,
     "end": 11.62
    },
    {
     "text": "invoke",
     "start": 11.62,
     "end": 11.81
    },
    {
     "text": "and",
     "start": 11.81,
     "end": 12.04
    },
    {
     "text": "clone,",
     "start": 12.04,
     "end": 12.48
    },
    {
     "text": "plus",
     "start": 12.48,
     "end": 12.7
    },
    {
     "text": "a",
     "start": 12.7,
     "end": 12.74
    },
    {
     "text": "templated",
     "start": 12.74,
     "end": 13.24
    },
    {
     "text": "holder",
     "start": 13.24,
     "end": 13.62
    },
    {
     "text": "that",
     "start": 13.62,
     "end": 13.87
    },
    {
     "text": "stores",
     "start": 13.87,
     "end": 14.29
    },
    {
     "text": "the",
     "start": 14.29,
     "end": 14.44
    },
    {
     "text": "real",
     "start": 14.44,
     "end": 14.69
    },
    {
     "text": "lambda,",
     "start": 14.69,
     "end": 15.19
    },
    {
     "text": "function",
     "start": 15.19,
     "end": 15.7
    },
    {
     "text": "pointer,",
     "start": 15.7,
     "end": 16.27
    },
    {
     "text": "or",
     "start": 16.27,
     "end": 16.39
    },
    {
     "text": "functor.",
     "start": 16.39,
     "end": 17.12
    },
    {
     "text": "The",
     "start": 17.12,
     "end": 17.33
    },
    {
     "text": "wrapper",
     "start": 17.33,
     "end": 17.82
    },
    {
     "text": "owns",
     "start": 17.82,
     "end": 18.17
    },
    {
     "text": "a",
     "start": 18.17,
     "end": 18.18
    },
    {
     "text": "unique",
     "start": 18.18,
     "end": 18.59
    },
    {
     "text": "pointer",
     "start": 18.59,
     "end": 19.08
    },
    {
     "text": "to",
     "start": 19.08,
     "end": 19.22
    },
    {
     "text": "that",
     "start": 19.22,
     "end": 19.5
    },
    {
     "text": "base.",
     "start": 19.5,
     "end": 20.0
    },
    {
     "text": "Clone",
     "start": 20.0,
     "end": 20.3
    },
    {
     "text": "gives",
     "start": 20.3,
     "end": 20.6
    },
    {
     "text": "it",
     "start": 20.6,
     "end": 20.72
    },
    {
     "text": "value",
     "start": 20.72,
     "end": 21.06
    },
    {
     "text": "semantics,",
     "start": 21.06,
     "end": 21.68
    },
    {
     "text": "and",
     "start": 21.68,
     "end": 21.86
    },
    {
     "text": "decay",
     "start": 21.86,
     "end": 22.16
    },
    {
     "text": "strips",
     "start": 22.16,
     "end": 22.52
    },
    {
     "text": "references",
     "start": 22.52,
     "end": 23.16
    },
    {
     "text": "so",
     "start": 23.16,
     "end": 23.24
    },
    {
     "text": "the",
     "start": 23.24,
     "end": 23.78
    },
    {
     "text": "holder",
     "start": 23.78,
     "end": 23.78
    },
    {
     "text": "owns",
     "start": 23.78,
     "end": 24.02
    },
    {
     "text": "a",
     "start": 24.02,
     "end": 24.08
    },
    {
     "text": "clean",
     "start": 24.08,
     "end": 24.4
    },
    {
     "text": "copy.",
     "start": 24.4,
     "end": 25.4
    },
    {
     "text": "The",
     "start": 25.48,
     "end": 25.61
    },
    {
     "text": "price",
     "start": 25.61,
     "end": 25.96
    },
    {
     "text": "is",
     "start": 25.96,
     "end": 26.04
    },
    {
     "text": "a",
     "start": 26.04,
     "end": 26.1
    },
    {
     "text": "heap",
     "start": 26.1,
     "end": 26.46
    },
    {
     "text": "allocation",
     "start": 26.46,
     "end": 27.0
    },
    {
     "text": "and",
     "start": 27.0,
     "end": 27.25
    },
    {
     "text": "a",
     "start": 27.25,
     "end": 27.25
    },
    {
     "text": "virtual",
     "start": 27.25,
     "end": 27.7
    },
    {
     "text": "call,",
     "start": 27.7,
     "end": 28.08
    },
    {
     "text": "softened",
     "start": 28.08,
     "end": 28.59
    },
    {
     "text": "in",
     "start": 28.59,
     "end": 28.72
    },
    {
     "text": "real",
     "start": 28.72,
     "end": 29.18
    },
    {
     "text": "libraries",
     "start": 29.18,
     "end": 29.56
    },
    {
     "text": "by",
     "start": 29.56,
     "end": 29.69
    },
    {
     "text": "small",
     "start": 29.69,
     "end": 30.08
    },
    {
     "text": "buffer",
     "start": 30.08,
     "end": 30.64
    },
    {
     "text": "optimization.",
     "start": 30.64,
     "end": 31.92
    },
    {
     "text": "Use",
     "start": 31.92,
     "end": 32.09
    },
    {
     "text": "it",
     "start": 32.09,
     "end": 32.2
    },
    {
     "text": "for",
     "start": 32.2,
     "end": 32.37
    },
    {
     "text": "stored",
     "start": 32.37,
     "end": 32.72
    },
    {
     "text": "callbacks",
     "start": 32.72,
     "end": 33.24
    },
    {
     "text": "and",
     "start": 33.24,
     "end": 33.41
    },
    {
     "text": "templates",
     "start": 33.41,
     "end": 33.96
    },
    {
     "text": "on",
     "start": 33.96,
     "end": 34.05
    },
    {
     "text": "hot",
     "start": 34.05,
     "end": 34.22
    },
    {
     "text": "paths.",
     "start": 34.22,
     "end": 34.78
    }
   ]
  },
  {
   "id": "05",
   "scene": "Name every capture",
   "audio": "assets/voice/05.wav",
   "start": 124.824,
   "duration": 32.251,
   "words": [
    {
     "text": "Question",
     "start": 0.04,
     "end": 0.75
    },
    {
     "text": "4",
     "start": 0.75,
     "end": 1.1
    },
    {
     "text": "capture",
     "start": 1.1,
     "end": 1.64
    },
    {
     "text": "modes.",
     "start": 1.64,
     "end": 2.2
    },
    {
     "text": "Empty",
     "start": 2.2,
     "end": 2.53
    },
    {
     "text": "brackets",
     "start": 2.53,
     "end": 3.06
    },
    {
     "text": "capture",
     "start": 3.06,
     "end": 3.57
    },
    {
     "text": "nothing,",
     "start": 3.57,
     "end": 4.18
    },
    {
     "text": "equals",
     "start": 4.18,
     "end": 4.52
    },
    {
     "text": "copies,",
     "start": 4.52,
     "end": 5.0
    },
    {
     "text": "ampersand",
     "start": 5.0,
     "end": 5.48
    },
    {
     "text": "references",
     "start": 5.48,
     "end": 6.32
    },
    {
     "text": "and",
     "start": 6.32,
     "end": 6.53
    },
    {
     "text": "you",
     "start": 6.53,
     "end": 6.7
    },
    {
     "text": "can",
     "start": 6.7,
     "end": 6.89
    },
    {
     "text": "mix",
     "start": 6.89,
     "end": 7.08
    },
    {
     "text": "them",
     "start": 7.08,
     "end": 7.42
    },
    {
     "text": "per",
     "start": 7.42,
     "end": 7.53
    },
    {
     "text": "variable.",
     "start": 7.53,
     "end": 8.51
    },
    {
     "text": "The",
     "start": 8.51,
     "end": 8.53
    },
    {
     "text": "defaults",
     "start": 8.53,
     "end": 9.21
    },
    {
     "text": "hide",
     "start": 9.21,
     "end": 9.55
    },
    {
     "text": "two",
     "start": 9.55,
     "end": 9.8
    },
    {
     "text": "traps.",
     "start": 9.8,
     "end": 10.55
    },
    {
     "text": "Capture",
     "start": 10.55,
     "end": 10.81
    },
    {
     "text": "by",
     "start": 10.81,
     "end": 10.97
    },
    {
     "text": "reference",
     "start": 10.97,
     "end": 11.29
    },
    {
     "text": "return",
     "start": 11.29,
     "end": 11.64
    },
    {
     "text": "the",
     "start": 11.64,
     "end": 11.85
    },
    {
     "text": "lambda",
     "start": 11.85,
     "end": 12.22
    },
    {
     "text": "and",
     "start": 12.22,
     "end": 12.41
    },
    {
     "text": "the",
     "start": 12.41,
     "end": 12.6
    },
    {
     "text": "local",
     "start": 12.6,
     "end": 12.92
    },
    {
     "text": "it",
     "start": 12.92,
     "end": 13.05
    },
    {
     "text": "points",
     "start": 13.05,
     "end": 13.57
    },
    {
     "text": "to",
     "start": 13.57,
     "end": 13.7
    },
    {
     "text": "is",
     "start": 13.7,
     "end": 13.83
    },
    {
     "text": "already",
     "start": 13.83,
     "end": 14.17
    },
    {
     "text": "destroyed.",
     "start": 14.17,
     "end": 15.0
    },
    {
     "text": "A",
     "start": 15.0,
     "end": 15.06
    },
    {
     "text": "dangling",
     "start": 15.06,
     "end": 15.68
    },
    {
     "text": "reference.",
     "start": 15.68,
     "end": 16.41
    },
    {
     "text": "Capture",
     "start": 16.41,
     "end": 16.92
    },
    {
     "text": "by",
     "start": 16.92,
     "end": 17.06
    },
    {
     "text": "value",
     "start": 17.06,
     "end": 17.48
    },
    {
     "text": "in",
     "start": 17.48,
     "end": 17.56
    },
    {
     "text": "a",
     "start": 17.56,
     "end": 17.63
    },
    {
     "text": "hot",
     "start": 17.63,
     "end": 17.84
    },
    {
     "text": "path,",
     "start": 17.84,
     "end": 18.13
    },
    {
     "text": "and",
     "start": 18.13,
     "end": 18.34
    },
    {
     "text": "you",
     "start": 18.34,
     "end": 18.55
    },
    {
     "text": "may",
     "start": 18.55,
     "end": 19.11
    },
    {
     "text": "silently",
     "start": 19.11,
     "end": 19.34
    },
    {
     "text": "copy",
     "start": 19.34,
     "end": 19.64
    },
    {
     "text": "an",
     "start": 19.64,
     "end": 19.81
    },
    {
     "text": "entire",
     "start": 19.81,
     "end": 20.2
    },
    {
     "text": "order",
     "start": 20.2,
     "end": 20.56
    },
    {
     "text": "book.",
     "start": 20.56,
     "end": 21.15
    },
    {
     "text": "Capturing",
     "start": 21.15,
     "end": 21.71
    },
    {
     "text": "this",
     "start": 21.71,
     "end": 22.08
    },
    {
     "text": "has",
     "start": 22.08,
     "end": 22.36
    },
    {
     "text": "the",
     "start": 22.36,
     "end": 22.64
    },
    {
     "text": "same",
     "start": 22.64,
     "end": 22.97
    },
    {
     "text": "lifetime",
     "start": 22.97,
     "end": 23.64
    },
    {
     "text": "risk.",
     "start": 23.64,
     "end": 24.28
    },
    {
     "text": "While",
     "start": 24.28,
     "end": 24.68
    },
    {
     "text": "C++17's",
     "start": 24.68,
     "end": 25.4
    },
    {
     "text": "star",
     "start": 25.4,
     "end": 25.72
    },
    {
     "text": "this",
     "start": 25.72,
     "end": 26.12
    },
    {
     "text": "takes",
     "start": 26.12,
     "end": 26.44
    },
    {
     "text": "a",
     "start": 26.44,
     "end": 26.52
    },
    {
     "text": "snapshot",
     "start": 26.52,
     "end": 27.16
    },
    {
     "text": "instead.",
     "start": 27.16,
     "end": 28.0
    },
    {
     "text": "The production rule:",
     "start": 28.04,
     "end": 29.18
    },
    {
     "text": "Name",
     "start": 29.18,
     "end": 29.45
    },
    {
     "text": "every",
     "start": 29.45,
     "end": 30.19
    },
    {
     "text": "capture",
     "start": 30.19,
     "end": 30.26
    },
    {
     "text": "so",
     "start": 30.26,
     "end": 30.39
    },
    {
     "text": "lifetimes",
     "start": 30.39,
     "end": 30.99
    },
    {
     "text": "are",
     "start": 30.99,
     "end": 31.22
    },
    {
     "text": "visible",
     "start": 31.22,
     "end": 31.57
    },
    {
     "text": "in",
     "start": 31.57,
     "end": 31.71
    },
    {
     "text": "review.",
     "start": 31.71,
     "end": 32.2
    }
   ]
  },
  {
   "id": "06",
   "scene": "State inside the lambda",
   "audio": "assets/voice/06.wav",
   "start": 157.675,
   "duration": 27.661,
   "words": [
    {
     "text": "Question",
     "start": 0.04,
     "end": 0.57
    },
    {
     "text": "5.",
     "start": 0.57,
     "end": 1.0
    },
    {
     "text": "Mutable",
     "start": 1.0,
     "end": 1.63
    },
    {
     "text": "lambdas.",
     "start": 1.63,
     "end": 2.49
    },
    {
     "text": "A",
     "start": 2.49,
     "end": 2.56
    },
    {
     "text": "lambda's call",
     "start": 2.56,
     "end": 3.35
    },
    {
     "text": "operator",
     "start": 3.35,
     "end": 3.93
    },
    {
     "text": "is",
     "start": 3.93,
     "end": 4.16
    },
    {
     "text": "const",
     "start": 4.16,
     "end": 4.48
    },
    {
     "text": "by",
     "start": 4.48,
     "end": 4.57
    },
    {
     "text": "default,",
     "start": 4.57,
     "end": 5.2
    },
    {
     "text": "so",
     "start": 5.2,
     "end": 5.29
    },
    {
     "text": "a",
     "start": 5.29,
     "end": 5.34
    },
    {
     "text": "captured",
     "start": 5.34,
     "end": 5.7
    },
    {
     "text": "copy",
     "start": 5.7,
     "end": 6.11
    },
    {
     "text": "cannot",
     "start": 6.11,
     "end": 6.73
    },
    {
     "text": "change.",
     "start": 6.73,
     "end": 7.88
    },
    {
     "text": "Mark",
     "start": 7.88,
     "end": 7.98
    },
    {
     "text": "it",
     "start": 7.98,
     "end": 8.01
    },
    {
     "text": "mutable,",
     "start": 8.01,
     "end": 8.43
    },
    {
     "text": "and",
     "start": 8.43,
     "end": 8.58
    },
    {
     "text": "the",
     "start": 8.58,
     "end": 8.73
    },
    {
     "text": "lambda",
     "start": 8.73,
     "end": 9.03
    },
    {
     "text": "may",
     "start": 9.03,
     "end": 9.2
    },
    {
     "text": "modify",
     "start": 9.2,
     "end": 9.56
    },
    {
     "text": "its",
     "start": 9.56,
     "end": 9.9
    },
    {
     "text": "own",
     "start": 9.9,
     "end": 10.24
    },
    {
     "text": "copy.",
     "start": 10.24,
     "end": 11.04
    },
    {
     "text": "Call",
     "start": 11.04,
     "end": 11.27
    },
    {
     "text": "the",
     "start": 11.27,
     "end": 11.28
    },
    {
     "text": "counter",
     "start": 11.28,
     "end": 11.54
    },
    {
     "text": "twice,",
     "start": 11.54,
     "end": 12.07
    },
    {
     "text": "and",
     "start": 12.07,
     "end": 12.25
    },
    {
     "text": "it",
     "start": 12.25,
     "end": 12.43
    },
    {
     "text": "returns",
     "start": 12.43,
     "end": 12.89
    },
    {
     "text": "1",
     "start": 12.89,
     "end": 13.1
    },
    {
     "text": "then",
     "start": 13.1,
     "end": 13.37
    },
    {
     "text": "2,",
     "start": 13.37,
     "end": 13.85
    },
    {
     "text": "while",
     "start": 13.85,
     "end": 14.09
    },
    {
     "text": "the",
     "start": 14.09,
     "end": 14.36
    },
    {
     "text": "original",
     "start": 14.36,
     "end": 14.87
    },
    {
     "text": "variable",
     "start": 14.87,
     "end": 15.44
    },
    {
     "text": "still",
     "start": 15.44,
     "end": 15.8
    },
    {
     "text": "reads",
     "start": 15.8,
     "end": 16.16
    },
    {
     "text": "0.",
     "start": 16.16,
     "end": 16.68
    },
    {
     "text": "That",
     "start": 16.68,
     "end": 16.78
    },
    {
     "text": "makes",
     "start": 16.78,
     "end": 16.92
    },
    {
     "text": "mutable",
     "start": 16.92,
     "end": 17.45
    },
    {
     "text": "a",
     "start": 17.45,
     "end": 17.5
    },
    {
     "text": "natural",
     "start": 17.5,
     "end": 18.01
    },
    {
     "text": "fit",
     "start": 18.01,
     "end": 18.23
    },
    {
     "text": "for",
     "start": 18.23,
     "end": 18.45
    },
    {
     "text": "generators,",
     "start": 18.45,
     "end": 19.32
    },
    {
     "text": "round",
     "start": 19.32,
     "end": 19.74
    },
    {
     "text": "robin",
     "start": 19.74,
     "end": 20.04
    },
    {
     "text": "dispatchers,",
     "start": 20.04,
     "end": 20.97
    },
    {
     "text": "and",
     "start": 20.97,
     "end": 21.19
    },
    {
     "text": "lambdas",
     "start": 21.19,
     "end": 21.67
    },
    {
     "text": "that",
     "start": 21.67,
     "end": 22.06
    },
    {
     "text": "own",
     "start": 22.06,
     "end": 22.2
    },
    {
     "text": "a",
     "start": 22.2,
     "end": 22.34
    },
    {
     "text": "moved",
     "start": 22.34,
     "end": 22.73
    },
    {
     "text": "in",
     "start": 22.73,
     "end": 22.88
    },
    {
     "text": "unique",
     "start": 22.88,
     "end": 23.34
    },
    {
     "text": "pointer.",
     "start": 23.34,
     "end": 24.09
    },
    {
     "text": "The",
     "start": 24.09,
     "end": 24.64
    },
    {
     "text": "state",
     "start": 24.64,
     "end": 24.68
    },
    {
     "text": "lives",
     "start": 24.68,
     "end": 25.02
    },
    {
     "text": "inside",
     "start": 25.02,
     "end": 25.42
    },
    {
     "text": "the",
     "start": 25.42,
     "end": 25.62
    },
    {
     "text": "lambda",
     "start": 25.62,
     "end": 26.02
    },
    {
     "text": "object,",
     "start": 26.02,
     "end": 26.6
    },
    {
     "text": "not",
     "start": 26.6,
     "end": 26.82
    },
    {
     "text": "in",
     "start": 26.82,
     "end": 26.87
    },
    {
     "text": "shared",
     "start": 26.87,
     "end": 27.47
    },
    {
     "text": "scope.",
     "start": 27.47,
     "end": 27.62
    }
   ]
  },
  {
   "id": "07",
   "scene": "A lambda has no name",
   "audio": "assets/voice/07.wav",
   "start": 185.936,
   "duration": 28.643,
   "words": [
    {
     "text": "Question",
     "start": 0.04,
     "end": 0.76
    },
    {
     "text": "6",
     "start": 0.76,
     "end": 0.97
    },
    {
     "text": "Recursive",
     "start": 0.97,
     "end": 1.76
    },
    {
     "text": "lambdas.",
     "start": 1.76,
     "end": 2.61
    },
    {
     "text": "A",
     "start": 2.61,
     "end": 2.67
    },
    {
     "text": "lambda",
     "start": 2.67,
     "end": 3.05
    },
    {
     "text": "has",
     "start": 3.05,
     "end": 3.23
    },
    {
     "text": "no",
     "start": 3.23,
     "end": 3.35
    },
    {
     "text": "name",
     "start": 3.35,
     "end": 3.6
    },
    {
     "text": "so",
     "start": 3.6,
     "end": 3.76
    },
    {
     "text": "it",
     "start": 3.76,
     "end": 3.84
    },
    {
     "text": "cannot",
     "start": 3.84,
     "end": 4.22
    },
    {
     "text": "call",
     "start": 4.22,
     "end": 4.54
    },
    {
     "text": "itself",
     "start": 4.54,
     "end": 5.01
    },
    {
     "text": "directly.",
     "start": 5.01,
     "end": 6.0
    },
    {
     "text": "The",
     "start": 6.0,
     "end": 6.2
    },
    {
     "text": "easy",
     "start": 6.2,
     "end": 6.44
    },
    {
     "text": "fix",
     "start": 6.44,
     "end": 6.63
    },
    {
     "text": "stores",
     "start": 6.63,
     "end": 7.01
    },
    {
     "text": "it",
     "start": 7.01,
     "end": 7.13
    },
    {
     "text": "in",
     "start": 7.13,
     "end": 7.25
    },
    {
     "text": "a",
     "start": 7.25,
     "end": 7.33
    },
    {
     "text": "std::function",
     "start": 7.33,
     "end": 8.45
    },
    {
     "text": "that",
     "start": 8.45,
     "end": 8.58
    },
    {
     "text": "captures",
     "start": 8.58,
     "end": 9.1
    },
    {
     "text": "itself",
     "start": 9.1,
     "end": 9.47
    },
    {
     "text": "by",
     "start": 9.47,
     "end": 9.59
    },
    {
     "text": "reference,",
     "start": 9.59,
     "end": 10.46
    },
    {
     "text": "but",
     "start": 10.46,
     "end": 10.52
    },
    {
     "text": "every",
     "start": 10.52,
     "end": 10.72
    },
    {
     "text": "recursive",
     "start": 10.72,
     "end": 11.4
    },
    {
     "text": "call",
     "start": 11.4,
     "end": 11.7
    },
    {
     "text": "pays",
     "start": 11.7,
     "end": 12.05
    },
    {
     "text": "for",
     "start": 12.05,
     "end": 12.22
    },
    {
     "text": "type",
     "start": 12.22,
     "end": 12.52
    },
    {
     "text": "erasure.",
     "start": 12.52,
     "end": 13.32
    },
    {
     "text": "The",
     "start": 13.32,
     "end": 13.49
    },
    {
     "text": "zero",
     "start": 13.49,
     "end": 13.72
    },
    {
     "text": "overhead",
     "start": 13.72,
     "end": 14.19
    },
    {
     "text": "fix",
     "start": 14.19,
     "end": 14.35
    },
    {
     "text": "passes",
     "start": 14.35,
     "end": 14.73
    },
    {
     "text": "the",
     "start": 14.73,
     "end": 14.88
    },
    {
     "text": "lambda",
     "start": 14.88,
     "end": 15.22
    },
    {
     "text": "to",
     "start": 15.22,
     "end": 15.42
    },
    {
     "text": "itself.",
     "start": 15.42,
     "end": 16.52
    },
    {
     "text": "A",
     "start": 16.52,
     "end": 16.6
    },
    {
     "text": "generic",
     "start": 16.6,
     "end": 17.08
    },
    {
     "text": "lambda",
     "start": 17.08,
     "end": 17.47
    },
    {
     "text": "takes",
     "start": 17.47,
     "end": 17.85
    },
    {
     "text": "auto",
     "start": 17.85,
     "end": 18.08
    },
    {
     "text": "reference",
     "start": 18.08,
     "end": 18.96
    },
    {
     "text": "self",
     "start": 18.96,
     "end": 18.98
    },
    {
     "text": "and",
     "start": 18.98,
     "end": 19.17
    },
    {
     "text": "calls",
     "start": 19.17,
     "end": 19.51
    },
    {
     "text": "self",
     "start": 19.51,
     "end": 19.78
    },
    {
     "text": "with",
     "start": 19.78,
     "end": 20.05
    },
    {
     "text": "self.",
     "start": 20.05,
     "end": 20.64
    },
    {
     "text": "A",
     "start": 20.64,
     "end": 20.69
    },
    {
     "text": "named",
     "start": 20.69,
     "end": 20.97
    },
    {
     "text": "functor",
     "start": 20.97,
     "end": 21.4
    },
    {
     "text": "struct",
     "start": 21.4,
     "end": 21.81
    },
    {
     "text": "is",
     "start": 21.81,
     "end": 21.96
    },
    {
     "text": "the",
     "start": 21.96,
     "end": 22.16
    },
    {
     "text": "most",
     "start": 22.16,
     "end": 22.41
    },
    {
     "text": "explicit",
     "start": 22.41,
     "end": 22.96
    },
    {
     "text": "option,",
     "start": 22.96,
     "end": 23.7
    },
    {
     "text": "and",
     "start": 23.7,
     "end": 23.83
    },
    {
     "text": "it",
     "start": 23.83,
     "end": 23.86
    },
    {
     "text": "can",
     "start": 23.86,
     "end": 24.03
    },
    {
     "text": "be",
     "start": 24.03,
     "end": 24.16
    },
    {
     "text": "stored",
     "start": 24.16,
     "end": 24.57
    },
    {
     "text": "without",
     "start": 24.57,
     "end": 25.03
    },
    {
     "text": "a",
     "start": 25.03,
     "end": 25.16
    },
    {
     "text": "wrapper.",
     "start": 25.16,
     "end": 25.88
    },
    {
     "text": "On",
     "start": 25.88,
     "end": 25.97
    },
    {
     "text": "a",
     "start": 25.97,
     "end": 26.01
    },
    {
     "text": "critical",
     "start": 26.01,
     "end": 26.38
    },
    {
     "text": "path,",
     "start": 26.42,
     "end": 26.71
    },
    {
     "text": "choose",
     "start": 26.71,
     "end": 27.05
    },
    {
     "text": "self-passing",
     "start": 27.05,
     "end": 27.71
    },
    {
     "text": "or",
     "start": 27.71,
     "end": 27.83
    },
    {
     "text": "the",
     "start": 27.83,
     "end": 27.99
    },
    {
     "text": "struct.",
     "start": 27.99,
     "end": 28.6
    }
   ]
  },
  {
   "id": "08",
   "scene": "auto makes a template",
   "audio": "assets/voice/08.wav",
   "start": 215.179,
   "duration": 35.597,
   "words": [
    {
     "text": "Question",
     "start": 0.04,
     "end": 0.57
    },
    {
     "text": "7.",
     "start": 0.57,
     "end": 1.01
    },
    {
     "text": "Generic",
     "start": 1.01,
     "end": 1.7
    },
    {
     "text": "lambdas.",
     "start": 1.7,
     "end": 2.48
    },
    {
     "text": "An",
     "start": 2.48,
     "end": 2.6
    },
    {
     "text": "auto",
     "start": 2.6,
     "end": 2.84
    },
    {
     "text": "parameter",
     "start": 2.84,
     "end": 3.39
    },
    {
     "text": "turns",
     "start": 3.39,
     "end": 3.69
    },
    {
     "text": "the",
     "start": 3.69,
     "end": 3.87
    },
    {
     "text": "call",
     "start": 3.87,
     "end": 4.11
    },
    {
     "text": "operator",
     "start": 4.11,
     "end": 4.64
    },
    {
     "text": "into",
     "start": 4.64,
     "end": 4.83
    },
    {
     "text": "a",
     "start": 4.83,
     "end": 4.94
    },
    {
     "text": "template.",
     "start": 4.94,
     "end": 6.08
    },
    {
     "text": "So",
     "start": 6.08,
     "end": 6.08
    },
    {
     "text": "the",
     "start": 6.08,
     "end": 6.29
    },
    {
     "text": "compiler",
     "start": 6.29,
     "end": 6.85
    },
    {
     "text": "stamps",
     "start": 6.85,
     "end": 7.27
    },
    {
     "text": "out",
     "start": 7.27,
     "end": 7.51
    },
    {
     "text": "a",
     "start": 7.51,
     "end": 7.55
    },
    {
     "text": "version",
     "start": 7.55,
     "end": 8.0
    },
    {
     "text": "for",
     "start": 8.0,
     "end": 8.5
    },
    {
     "text": "each",
     "start": 8.5,
     "end": 8.53
    },
    {
     "text": "argument",
     "start": 8.53,
     "end": 9.09
    },
    {
     "text": "type,",
     "start": 9.09,
     "end": 9.51
    },
    {
     "text": "fully",
     "start": 9.51,
     "end": 9.85
    },
    {
     "text": "inlined.",
     "start": 9.85,
     "end": 10.64
    },
    {
     "text": "C++20",
     "start": 10.64,
     "end": 11.98
    },
    {
     "text": "adds",
     "start": 11.98,
     "end": 12.09
    },
    {
     "text": "explicit",
     "start": 12.09,
     "end": 12.52
    },
    {
     "text": "template",
     "start": 12.52,
     "end": 13.08
    },
    {
     "text": "parameters,",
     "start": 13.08,
     "end": 13.95
    },
    {
     "text": "which",
     "start": 13.95,
     "end": 14.28
    },
    {
     "text": "can",
     "start": 14.28,
     "end": 14.44
    },
    {
     "text": "force",
     "start": 14.44,
     "end": 14.94
    },
    {
     "text": "both",
     "start": 14.94,
     "end": 15.12
    },
    {
     "text": "arguments",
     "start": 15.12,
     "end": 15.79
    },
    {
     "text": "to",
     "start": 15.79,
     "end": 15.89
    },
    {
     "text": "share",
     "start": 15.89,
     "end": 16.24
    },
    {
     "text": "one",
     "start": 16.24,
     "end": 16.47
    },
    {
     "text": "type.",
     "start": 16.47,
     "end": 17.0
    },
    {
     "text": "Pass",
     "start": 17.0,
     "end": 17.18
    },
    {
     "text": "a",
     "start": 17.18,
     "end": 17.22
    },
    {
     "text": "generic",
     "start": 17.22,
     "end": 17.56
    },
    {
     "text": "comparator",
     "start": 17.56,
     "end": 18.19
    },
    {
     "text": "straight",
     "start": 18.19,
     "end": 18.7
    },
    {
     "text": "to",
     "start": 18.7,
     "end": 18.82
    },
    {
     "text": "sort.",
     "start": 18.82,
     "end": 19.26
    },
    {
     "text": "And",
     "start": 19.26,
     "end": 19.44
    },
    {
     "text": "it",
     "start": 19.44,
     "end": 19.55
    },
    {
     "text": "inlines,",
     "start": 19.55,
     "end": 20.13
    },
    {
     "text": "unlike",
     "start": 20.13,
     "end": 20.51
    },
    {
     "text": "std::function,",
     "start": 20.51,
     "end": 21.65
    },
    {
     "text": "which",
     "start": 21.65,
     "end": 21.97
    },
    {
     "text": "pays",
     "start": 21.97,
     "end": 22.22
    },
    {
     "text": "a",
     "start": 22.22,
     "end": 22.28
    },
    {
     "text": "virtual",
     "start": 22.28,
     "end": 22.86
    },
    {
     "text": "call",
     "start": 22.86,
     "end": 23.21
    },
    {
     "text": "per",
     "start": 23.21,
     "end": 23.47
    },
    {
     "text": "comparison.",
     "start": 23.47,
     "end": 24.64
    },
    {
     "text": "That",
     "start": 24.64,
     "end": 25.06
    },
    {
     "text": "is",
     "start": 25.06,
     "end": 25.27
    },
    {
     "text": "the",
     "start": 25.27,
     "end": 25.29
    },
    {
     "text": "walkthrough.",
     "start": 25.29,
     "end": 26.3
    },
    {
     "text": "Keep",
     "start": 26.3,
     "end": 26.59
    },
    {
     "text": "functions",
     "start": 26.59,
     "end": 27.24
    },
    {
     "text": "pure,",
     "start": 27.24,
     "end": 27.69
    },
    {
     "text": "pass",
     "start": 27.69,
     "end": 27.94
    },
    {
     "text": "behavior",
     "start": 27.94,
     "end": 28.59
    },
    {
     "text": "as",
     "start": 28.59,
     "end": 28.85
    },
    {
     "text": "values,",
     "start": 28.85,
     "end": 29.32
    },
    {
     "text": "scope resources",
     "start": 29.36,
     "end": 30.12
    },
    {
     "text": "with",
     "start": 30.12,
     "end": 30.36
    },
    {
     "text": "higher",
     "start": 30.36,
     "end": 30.76
    },
    {
     "text": "order",
     "start": 30.76,
     "end": 31.03
    },
    {
     "text": "functions,",
     "start": 31.03,
     "end": 31.75
    },
    {
     "text": "name",
     "start": 31.75,
     "end": 31.96
    },
    {
     "text": "your",
     "start": 31.96,
     "end": 32.26
    },
    {
     "text": "captures,",
     "start": 32.26,
     "end": 32.83
    },
    {
     "text": "and",
     "start": 32.83,
     "end": 32.99
    },
    {
     "text": "save",
     "start": 32.99,
     "end": 33.27
    },
    {
     "text": "type",
     "start": 33.27,
     "end": 33.47
    },
    {
     "text": "erasure",
     "start": 33.47,
     "end": 34.0
    },
    {
     "text": "for",
     "start": 34.0,
     "end": 34.21
    },
    {
     "text": "when",
     "start": 34.21,
     "end": 34.42
    },
    {
     "text": "you",
     "start": 34.42,
     "end": 34.6
    },
    {
     "text": "truly",
     "start": 34.6,
     "end": 34.89
    },
    {
     "text": "need",
     "start": 34.89,
     "end": 35.13
    },
    {
     "text": "storage.",
     "start": 35.13,
     "end": 35.56
    }
   ]
  }
 ]
};
